[package]
name = "rello"
version = "0.1.0"
authors = ["Geoff Cant <nem@erlang.geek.nz>"]

[dependencies]
log = "*"
env_logger = "*"

[dependencies.pencil]
path = "deps/pencil"

[target.heroku]
version = "stable"
